# Copyright © 2025 Seb Garrioch. All rights reserved.
# Published under the MIT License.

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Optimized Internals (CI)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    - name: "Setup .NET 9.0 SDK"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: "Restore Dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --no-restore

    - name: "Test"
      run: dotnet test --no-build --verbosity normal
